### ISSUE TITLE
Make path of api folder configurable

### ISSUE THREAD

**Issue by thomasaull** [Sebiworld/AppApi#1]
When using the Site [Profile Exporter Module](https://modules.processwire.com/modules/process-export-profile/) the API Routes and Endpoint Files would be missing, since they are not part of the `/templates` directory. It would make sense to either use `/templates` as the default directory for the `api` folder or to make the path configurable, like @Sebiworld mentioned in [this post](https://processwire.com/talk/topic/24014-new-module-appapi/?do=findComment&comment=204773)

**Comment by Sebiworld** [comment]
The path to Routes.php is now configurable in the module's settings, so you now should be able to change it to /site/templates/Routes.php or any other path! Thanks for your help!
