### ISSUE TITLE
Cannot create an application without making it the default application

### ISSUE THREAD

**Issue by twinklebob** [Sebiworld/AppApi#16]
The false value for the default application flag is not being correctly set.

### Replication steps:
1. On a v1.1 install create a new application
2. Set title, single jwt, expires in = 31536000
3. Try to save

### Expected outcome:
Application is saved

### Actual:
Error message: `Application: The application could not be saved: SQLSTATE[HY000]: General error: 1366 Incorrect integer value: '' for column 'default_application' at row 1`

**Comment by twinklebob** [comment]
Worse still, if you check the default application checkbox you get: `Application: The application could not be saved: SQLSTATE[HY093]: Invalid parameter number: number of bound variables does not match number of tokens`

**Comment by Sebiworld** [comment]
That's the same error that was mentioned in the forum 😭 
I still cannot reproduce it on my test systems with the same steps you listed. Do you have any clue? What db-configuration do you use? 
My first would be to use a different column-type instead of boolean, maybe thats the problem...

**Comment by twinklebob** [comment]
Ok, here's something interesting. My local dev environment uses MySQL on a laravel homestead (vagrant) environment. I can add an application fine there.

I'm just confirming the db setup on the test and production systems with the person who set it all up.

**Comment by twinklebob** [comment]
Can confirm that this doesn't happen with v1.1.1

**Comment by Sebiworld** [comment]
Great news! I think I will from now on try to avoid BOOLEAN-types in databases 👍

**Comment by twinklebob** [comment]
Just a little note, the two systems that had the problem, one was on MySQL and the other was on MariaDB. No idea why they failed but my local didn't :shrug:
