### ISSUE TITLE
Router.php uses $input->url to read URL, and converts path segments to lower case.

### ISSUE THREAD

**Issue by Pauldro** [Sebiworld/AppApi#17]
### Problem: Router.php uses $input->url to read URL, and converts path segments to lower case.

I'm using a route path which may have mixed case segments but when I use the router to call to my controller, the id passed is in lower case.

This is my route:
`['GET', '{id}/track/', Spotify::class, 'getPlaylistTrack']`

Router.php reads the URL using $input->url() which converts each segment to lowercase. 
`$url        = $this->wire('sanitizer')->url(wire('input')->url);`

Example:
_spotify.test/api/spotify/playlists/2lMt32mw3DyJ1x6E3uX42B/track/?trackID=6NMtzpDQBTOfJwMzgMX0zl&index=4_

This is the response and the ID parsed from the URL is in lower case.
```
{
    "it": "api/spotify/playlists/2lMt32mw3DyJ1x6E3uX42B/track/",
    "trackID": "6NMtzpDQBTOfJwMzgMX0zl",
    "index": 4,
    "id": "2lmt32mw3dyj1x6e3ux42b"
}
```

###  Weird Quirk, if I use another route, 
['GET', '{id}', Spotify::class, 'playlist']

_spotify.test/api/spotify/playlists/2lMt32mw3DyJ1x6E3uX42B/_
```
{
    "playlistID": "2lMt32mw3DyJ1x6E3uX42B"
}
```
I have a semi work around that replicates $input->url();
My question is should I be sending the mixed case parameter through the other methods since PW forces lowercase paths?
Or should the router adapt to handle it?

**Comment by Sebiworld** [comment]
Hi @Pauldro , thank you for submitting this issue! 
Since everything after the domain-name is allowed to be case-sensitive, we should make that possible in AppApi's Router as well. I will have a look at it as soon as I have some time. Feel free to submit a pull-request, if you already have a fix for that!

**Comment by Sebiworld** [comment]
Thank you @Pauldro , thank you again for your contribution to AppApi! With your descriptions I could reproduce the problem. It really seems to be Processwire's `wire('input')->url` function, that transfers everything to lowercase. But we do not need that function. Now the Router uses `$_SERVER['REQUEST_URI']` to get its initial url. And here we can have mixed-case paths.

I hope that solves your problem?

**Comment by Pauldro** [comment]
@Sebiworld I think it will, I'll have a chance to test it this afternoon. I love your module. I hope to add some contributions myself.
Thanks for being awesome!
