### ISSUE TITLE
Router::handleError should check error_reporting()

### ISSUE THREAD

**Issue by eelke** [Sebiworld/AppApi#20]
Currently the [Router::handleError()](https://github.com/Sebiworld/AppApi/blob/c385219caf1d3a5ade164f310100f3b2872ed93b/classes/Router.php#L288) function incorrectly reports HTTP 500 errors that result from methods that should have remained silent, because they are called with the error control operator '@'.

As the [PHP documentation](https://www.php.net/manual/en/language.operators.errorcontrol.php) on error control operators puts it: 

> If you have set a custom error handler function with set_error_handler() then it will still get called, but this custom error handler can (and should) call error_reporting() which will return 0 when the call that triggered the error was preceded by an @.

The solution is simple: just add a check error_reporting() before the handleError method, for instance

```PHP
    public static function handleError($errNo, $errStr, $errFile, $errLine) {
        if (error_reporting()) {
            $return = new \StdClass();
            $return->error = 'Internal Server Error';
            $return->devmessage = [
                'message' => $errStr,
                'location' => $errFile,
                'line' => $errLine
            ];
            self::displayOrLogError($return, 500);
        }
    }
```

(Also posted on ProcessWire forum)

**Comment by Sebiworld** [comment]
Thank you @eelke ! I haven't come across this problem yet, but the change definitely makes sense. I will now publish version 1.1.3 that will include this bugfix.
