### ISSUE TITLE
v1.1.3 breaks routes using query parameters

### ISSUE THREAD

**Issue by twinklebob** [Sebiworld/AppApi#22]
The change to using the REQUEST_URI has now introduced a problem whereby route matching was attempted using the query parameters which failed.

In our example we're using it to modify pagination: `v1/orders/page/1?limit=10` for example is trying to be matched against `v1/orders/page/{pageNum:\d+}`

Luckily we picked this up on a staging/testing server, I have already patched it locally. I'll drop a PR in.

**Comment by Sebiworld** [comment]
Oh no! Thank you @twinklebob!
Preventing breaking changes was actually my main goal, but I unfortunately overlooked this bug. I will look into your pull request and release it in v1.1.4 as soon as possible.
