### ISSUE TITLE
Apikey & Auth-token to be set as GET-params

### ISSUE THREAD

**Issue by pmichaelis** [Sebiworld/AppApi#28]
Hey,

the Changes says "Allows Apikey & Auth-token to be set as GET-params". Could you provide an example. 
I am working on a pw instance which runs an a ngnix and I have the feeling, hat there is something with the request headers, because it constantly says, no matter what I do.

 "error": "Apikey not valid."

Thanks for any hints

**Comment by Sebiworld** [comment]
Hey Philipp!

I needed this for one special use-case: Loading image-files from an api-endpoint. It's complicated to add a header to this, so I needed to include the api-key with a GET-param:
`<img src="https://my-domain/api/file/7845?api_key=aK2VasqdDaTCabutZvKjY&file=test-image.0x300.jpg">`
It is also possible to add an auth-token. That should be a GET-param named "authorization".

However, I would definitely recommend sending these parameters as headers whenever possible. GET parameters are, as far as I know, always written in the server logs. And therefore it would be good to enter no or as little as possible security-relevant information there. But as I said, I can't always avoid this completely and I'm still learning... 

Please let me know if you were able to find out anything about your header issues. If other people could run into these problems too, it might be useful to include that in the wiki here!

**Comment by pmichaelis** [comment]
Hey, I think the issue with the invalid token is connected to the php version (php8). I downgraded and it worked. Thanks for the details.

**Comment by adrianbj** [comment]
I am also running PHP8 and getting `"error": "Apikey not valid."` although in my case I am sending the API key in the headers, so maybe it's simply a PHP issue with this module in general?
https://processwire.com/talk/topic/24014-new-module-appapi/?do=findComment&comment=219765

**Comment by adrianbj** [comment]
@Sebiworld - just following up to say that there is definitely an issue with api key authorization with PHP8.

I am not seeing any useful errors logged anywhere which is weird, but my gut feeling is there might be an issue related to calling of non-static methods statically, but this will probably turn out to be wrong :)

**Comment by Sebiworld** [comment]
Hi @adrianbj ! 

I did some testing with PHP8. In my case, there were problems with basic authentication and the naming of the authorisation header. Sometimes the server added the prefix "REDIRECT_", and then the headers were of course no longer readable. With the improvements in the new [version 1.2.1](https://github.com/Sebiworld/AppApi/releases/tag/v1.2.1), I was able to fix these errors - in my server configuration, the AppApi module now runs under PHP 8.

Can you please test it again? I haven't had any direct problems with the Api key, but the changes in the handling of header names may have improved things there too. If you still have problems, I would be interested in a var_dump from the auth class in the initApiKey() function from the $headers variable. Maybe you have the api key under a different key in the array than I took into account?

**Comment by adrianbj** [comment]
Thanks for your work on this. I just updated to the new version and I still can't get the test route to work on PHP8. Again it's fine on 7. 

Here's the dump of `$headers`

Let me know if there is anything else I can provide.

```
{"USER":"www-data","HOME":"\/var\/www","SCRIPT_NAME":"\/index.php","REQUEST_URI":"\/api","QUERY_STRING":"it=api","REQUEST_METHOD":"POST","SERVER_PROTOCOL":"HTTP\/1.1","GATEWAY_INTERFACE":"CGI\/1.1","URL":"\/api","REMOTE_PORT":"51690","SCRIPT_FILENAME":"\/var\/www\/mysite.com\/index.php","SERVER_ADMIN":"me@gmail.com","CONTEXT_DOCUMENT_ROOT":"\/var\/www\/mysite.com","CONTEXT_PREFIX":"","REQUEST_SCHEME":"https","DOCUMENT_ROOT":"\/var\/www\/mysite.com","REMOTE_ADDR":"xxx","SERVER_PORT":"443","SERVER_ADDR":"xxx","SERVER_NAME":"mysite.com","SERVER_SOFTWARE":"Apache","SERVER_SIGNATURE":"","PATH":"\/usr\/local\/sbin:\/usr\/local\/bin:\/usr\/sbin:\/usr\/bin:\/sbin:\/bin","CONTENT_LENGTH":"0","COOKIE":"wires=p3savhrgm94qdgjd76nr6lrh1450","CONNECTION":"keep-alive","ACCEPT_ENCODING":"gzip, deflate, br","HOST":"mysite.com","POSTMAN_TOKEN":"088285f6-134f-4dff-b5dc-9f547b817752","CACHE_CONTROL":"no-cache","ACCEPT":"*\/*","USER_AGENT":"PostmanRuntime\/7.28.4","X_API_KEY":"T9Ze6e9W1N6Mp0SZYvkGm","PROXY-NOKEEPALIVE":"1","SSL_TLS_SNI":"mysite.com","HTTPS":"on","MOD_REWRITE":"On","PROTO":"https","SCRIPT_URI":"https:\/\/mysite.com\/api","SCRIPT_URL":"\/api","STATUS":"200","proto":"https","FCGI_ROLE":"RESPONDER","PHP_SELF":"\/index.php","REQUEST_TIME_FLOAT":1639331464.579094,"REQUEST_TIME":1639331464,"CONTENT-LENGTH":"0","ACCEPT-ENCODING":"gzip, deflate, br","POSTMAN-TOKEN":"088285f6-134f-4dff-b5dc-9f547b817752","CACHE-CONTROL":"no-cache","USER-AGENT":"PostmanRuntime\/7.28.4","X-API-KEY":"T9Ze6e9Wghjdd76h0SZYvkGm","MOD-REWRITE":"On"}
```

**Comment by Sebiworld** [comment]
@adrianbj  Mhm... I see that there is an `X-API-KEY` header present which should be used in the code after that. The error must be somewhere later in the code. 

Do you be any chance get a message, if you `var_dump()` the `\Throwable $e`  in line 45 of the same function (in `catch`)? 

Otherwise I would try to add a `var_dump` after every code line in between to see where the code fails. (Disclaimer: I know, not the most elegant way to debug, but the fastest and easiest :-) )

**Comment by adrianbj** [comment]
OK, I think I have tracked it down. For some reason every time I make a request it sets the Accessible Until time for the API to the current second which seems to be just before the `Apikey::isValid()` method runs. If I remove the those checks and make that method simply:
```
	public function ___isAccessable() {
		return $this->isValid();
	}
```

then everything works as expected. So I guess the real question is why the accessible until value is being set on each request. Let me know if you'd like me to go down that rabbit hole, or if you can figure it out from here.

Thanks.

**Comment by Sebiworld** [comment]
I like rabbit holes 😄 

Maybe its an issue with the default value for the datetime-field `accessable_until` in the table `appapi_apikeys`. I did not explicitly define a default - maybe thats the problem.  In my database-configuration it seems to default to unix 0 (01-01-1970), which I handle in the code. But maybe other databases fill in other default values? Could you please try to paste `NULL` into the database field?

**Comment by adrianbj** [comment]
I think you got it - it's not actually the sending of the request that sets that timestamp. When you save the API key settings, it sets it but you need to reload the settings page to see that it's been set. After emptying it and saving, it just collapses the field. Setting it to NULL manually in the DB table fixes things.

**Comment by Sebiworld** [comment]
I think I found the actual problem. PHP 8 seems to have changed how `date('Y-m-d G:i:s', NULL)` works. This seems to output the current date now. In PHP 7 it was "1970-01-01 1:00:00", which I handled correctly. But its better to write NULL to the database in that case. 

I am optimistic that this will solve the problem. Version 1.2.2 with the bug fix is coming soon! Thanks for your help @adrianbj !

**Comment by pmichaelis** [comment]
Great job, guys! So good.

**Comment by adrianbj** [comment]
Looks to be working great for me now - thanks!

**Comment by Sebiworld** [comment]
I am glad that this problem has been solved. I'm closing the issue - but feel free to open a new one if there's any other strange behaviour under PHP 8 anywhere else!
