### ISSUE TITLE
Installing module causes database error

### ISSUE THREAD

**Issue by Hurmeli** [Sebiworld/AppApi#38]
Trying to install this on our server causes:

`AppApi: Error creating db-tables: SQLSTATE[42000]: Syntax error or access violation: 1064 You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'JSON NOT NULL,
`token_secret` varchar(100) NOT NULL,
`expires_in` int(11' at line 10`

Rest of the error is missing. 

Trying to create new Application causes:

`The application could not be saved: SQLSTATE[42S02]: Base table or view not found: 1146...`

So something is breaking during installation.

Just posting this here incase there's something unorthodox going on with the modules installation. First time we've encountered this and we've done dozens of Processwire sites with many modules before.

**Comment by Sebiworld** [comment]
Thank you @Hurmeli !

I noticed problems with the installation routine a few days ago when I was working on another module. Somehow the code that is defined in the module in the ___install function doesn't seem to be executed anymore. As soon as I add my own ___install implementation, the installation throws an error. In the AppApi module, all database tables are created in this function.

I don't know yet exactly where this error comes from and I am debugging it. Right now I'm assuming a bug in the ProcessWire core, but I need to test further. Please let me know if you find out more in the meantime!

**Comment by Sebiworld** [comment]
Hey @Hurmeli,
I think your issue could be solved. I have found out that some versions of MariaDB seem to have problems with JSON for the database column type. It's recommended to use LONGTEXT instead, so I changed the db-initialization logic for it.
Please report back if the issue is still apparent!
