### ISSUE TITLE
Allow hook for Auth::currentUser() 

### ISSUE THREAD

**Issue by nloyola** [Sebiworld/AppApi#41]
When getting the current user via the `auth` route, I would like to add the user's roles to the reply. 

I can add a hook to [Auth::doLogin()](https://github.com/Sebiworld/AppApi/blob/8568f15fd6ecf2866d1b45ccb74d8d734e58fb13/classes/Auth.php#L116) to do this, but I cannot for [Auth::currentUser()](https://github.com/Sebiworld/AppApi/blob/8568f15fd6ecf2866d1b45ccb74d8d734e58fb13/classes/Auth.php#L605).

I can submit a pull request if it makes things easier.

Thanks

**Comment by Sebiworld** [comment]
Hi @nloyola ,
thank you for your request. You are right - we should make that function hookable! If you mind becoming an official "contributor" of this module, I would be glad if you can submit a pull request for that. 

I actually needed something similar for my app-project. You can overwrite the auth GET route to output custom user data. In my case, i wanted to return the user's roles and permissions. Have a look at my [Routes.php](https://github.com/Sebiworld/musical-fabrik.de/blob/master/site/api/Routes.php) and [GeneralApi.class.php](https://github.com/Sebiworld/musical-fabrik.de/blob/master/site/api/GeneralApi.class.php) to see how I have done that.

**Comment by nloyola** [comment]
Thanks for showing me your code @Sebiworld. I will definitely use something similar with the code I'm working with.

Pull request coming shortly.

**Comment by nloyola** [comment]
Pull request in #42.

**Comment by Sebiworld** [comment]
v1.3.2 with your pr is now out - sorry for the delay and thank you for making AppApi better!
