### ISSUE TITLE
Wiki has incorrect method for /api/auth/access (should be post, not get)

### ISSUE THREAD

**Issue by jlahijani** [Sebiworld/AppApi#43]
View this page:
https://github.com/Sebiworld/AppApi/wiki/2.4:-Double-JWT

It gives this example:
```
this.httpClient.get('https://my-website.dev/api/auth/access', {
  'x-api-key': 'ytaaYCMkUmouZawYMvJN9',
  authorization: 'Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJteS13ZWJzaXRlLmxvY2FsIiwiYXVkIjo0LCJzdWIiOjQxLCJpYXQiOjE1OTQ3NDk2OTUsIm5iZiI6MTU5NDc0OTY5NSwianRpIjoiSjdjTldsM3J0Q3VRSUN3azA2YW9LIiwiZXhwIjoxNTk3MzQxNjk1LCJzaWQiOiIxNDJhZmVhZG9jOTIybzJzZWJpaDciLCJzaWRfY2hhbGxlbmdlIjoiYmwwMzQyYXNpS0JIVS81a0g0Q0xWWGNzYWlNMTExOCJ9.9y4h0nslg2JHLSPFevOK-JWx2P_RfaaqSHRPi7nnSMk',
});
```

It's using a `get` method, but I believe it should be a `post` method (`get` won't work).  The auto-documentation in AppApi at `/admin/setup/appapi/endpoints` also lists it correctly as `post`.

**Comment by Sebiworld** [comment]
Hey @jlahijani , many thanks for your hint! You are absolutely right - to request an access token you have to send the refresh token to the server via POST request. Thanks again, the typo has now been fixed!
