### ISSUE TITLE
checkAndSanitizeRequiredParameters doesn't detect hookable sanitizer methods

### ISSUE THREAD

**Issue by jlahijani** [Sebiworld/AppApi#45]
I want to sanitize an array, and even though 'array' is a method on ProcessWire's sanitizer class, it's technically a hookable method and therefore the method name is `___array`.  As a result of, `checkAndSanitizeRequiredParameters` will not detect it and error.

This line should be changed from this:
```
if (!method_exists(wire('sanitizer'), $sanitizer)) {
```

To this:
```
if (!method_exists(wire('sanitizer'), $sanitizer) && !method_exists(wire('sanitizer'), '___'.$sanitizer)) {
```

**Comment by Sebiworld** [comment]
Works fine - the fix is included in the newest version 1.3.3. Thank you @jlahijani for your help!
